print("What is your favorite movie?", end=' ')
movie = input()
print("Who is your crush? I promise not to tell.", end=' ')
crush = input()
print("How are you feeling?", end=' ')
feels = input()

print(f"I watched {movie} last night. It was good.")
print(f"LOL. {crush} out of all people? I'm telling {crush}.")
print(f"So you're feeling {feels}. Man up and stop being a pussy.")